version: '3.9'

services:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: "app"
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    depends_on:
#      - database
#    networks:
#      - custom

  database:
    image: postgres:latest
    restart: always
    container_name: "database"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5460:5432"
    networks:
      - custom

  database_test:
    image: postgres:latest
    restart: always
    container_name: "database_test"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task_bd_test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5461:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge